### ISSUE TITLE
Thank you for your covering last week!

### ISSUE THREAD

**Issue by kaleocheng** [lnugraha/code-in-place-extra#1]
Hi Leo, I'm Kaleo and was not able to lead the fifth section. Thanks for your kindly help!

And one of the student is asking the YouTube you mentioned to them during  that section, would you mind to share the link here?

**Comment by lnugraha** [comment]
There are several YouTube videos, so I just list them below:
1. **Python with MIT:** [https://youtu.be/xAcTmDO6NTI?feature=shared](https://youtu.be/xAcTmDO6NTI?feature=shared)

2. **Python List:** [https://youtu.be/ohCDWZgNIU0?feature=shared](https://youtu.be/ohCDWZgNIU0?feature=shared)
3. **Python Dict:** [https://youtu.be/XCcpzWs-CI4?feature=shared](https://youtu.be/XCcpzWs-CI4?feature=shared)
4. **Python Tuples:** [https://youtu.be/NI26dqhs2Rk?feature=shared](https://youtu.be/NI26dqhs2Rk?feature=shared)
5. **Python Sets:** [https://youtu.be/sBvaPopWOmQ?feature=shared](https://youtu.be/sBvaPopWOmQ?feature=shared)

6. **Writing Functions:** [https://youtu.be/NE97ylAnrz4?feature=shared](https://youtu.be/NE97ylAnrz4?feature=shared)
7. **Unit Tests:** [https://youtu.be/1Lfv5tUGsn8?feature=shared](https://youtu.be/1Lfv5tUGsn8?feature=shared)
